"""Event names and Excursion type counts read off the game client.

Written by `python docs/client_tables.py --ship`, as of the game build
`BUILD`; never edited by hand. What a player's own client says wins
over these (`game_client`), so this is what a player sees whose client
the program could not find or read.

ASCII throughout: a name's other characters are written as escapes.
"""


BUILD = 88

# {schedule id: English name}. See game_client.event_names.
EVENT_NAMES = {
    'anniversary_banner_1': 'Enjoy the Festival',
    'chaos_exploration_1': 'Special Exploration Reward \u2014 Laboratory 0',
    'chaos_exploration_2': 'Special Exploration Reward - Burning Life',
    'commander_mission_1': 'Rookie Captain Mission',
    'countdown_attendance_1st': 'Nightmare Carnival',
    'disaster_daily_1': 'Galactic News Network',
    'disaster_daily_2': 'Galactic News Network',
    'disaster_daily_3': 'Galactic News Network',
    'disaster_daily_4': 'Galactic News Network',
    'disaster_s01': 'Galactic Disaster',
    'disaster_s02': 'Galactic Disaster',
    'disaster_s03': 'Galactic Disaster',
    'disaster_s04': 'Shattered Light and Claw',
    'disaster_s05_00': 'Escape from Judgment',
    'disaster_s2_event_operation': 'Operation: Firebreak',
    'ds_s3_event_rhythm_game': 'Melody at the Highest Peak',
    'event_1': 'Invitation to a New Journey',
    'event_10': 'Virtual Tactical Simulation',
    'event_100': 'Basin of Hyperspace - Dimensional Twilight',
    'event_101': 'Overdrive - Simulation',
    'event_102': 'Sweet Rewards After Missions',
    'event_103': 'Basin of Hyperspace - Dimensional Twilight',
    'event_104': 'Invitation to Dreams',
    'event_105': 'Virtual Tactical Simulation',
    'event_107': 'Melody at the Highest Peak',
    'event_108': '[Scoop] Up Close with Tenebria',
    'event_109': 'Zero System',
    'event_11': 'Basin of Hyperspace - Dimensional Twilight',
    'event_110': "Monsters' Arena",
    'event_111': 'A Story Rewritten',
    'event_112': 'Full-Scale Offensive',
    'event_113': 'Virtual Tactical Simulation',
    'event_114': "Rei's Gift",
    'event_115': 'Overdrive - Simulation',
    'event_116': 'Guardian of the Ark',
    'event_118': 'Basin of Hyperspace - Dimensional Twilight',
    'event_119': 'Basin of Hyperspace - Dimensional Twilight',
    'event_12': "Rei's Gift",
    'event_120': 'Sweet Rewards After Missions',
    'event_121': 'Overdrive - Simulation',
    'event_122': 'Shattered Light and Claw',
    'event_123': "Following the Fox's Footsteps",
    'event_124': 'Chasing the Remnants of Light',
    'event_125': 'Basin of Hyperspace - Dimensional Twilight',
    'event_126': 'Overdrive - Simulation',
    'event_127': 'Virtual Tactical Simulation',
    'event_128': 'Overdrive - Simulation',
    'event_129': 'Guardian of the Ark',
    'event_13': "Rei's Gift",
    'event_130': 'Basin of Hyperspace - Dimensional Twilight',
    'event_131': 'Zero System',
    'event_132': 'Beach Caf\xe9 Festival',
    'event_134': 'Virtual Tactical Simulation',
    'event_135': 'Virtual Tactical Simulation',
    'event_136': 'Primal Desire',
    'event_137': 'Stella Market',
    'event_138': 'Full-Scale Offensive',
    'event_139': 'Zero System',
    'event_14': 'Special Exploration Reward \u2014 Laboratory 0',
    'event_140': 'CZN x Epic Seven',
    'event_142': "Olga's Secret Diary \u2661",
    'event_143': "Rei's Gift",
    'event_144': 'Overdrive - Simulation',
    'event_145': 'Sweet Rewards After Missions',
    'event_146': 'SE-4 BR33ZE',
    'event_147': 'Basin of Hyperspace - Dimensional Twilight',
    'event_149': 'Escape from Judgment',
    'event_15': 'Guardian of the Ark',
    'event_150': 'Overdrive - Simulation',
    'event_151': 'Basin of Hyperspace - Dimensional Twilight',
    'event_153': 'Memoirs of the Ark Protection Bureau Chief',
    'event_154': "Guardian Angel's Vacation",
    'event_156': 'Zero System',
    'event_159': 'Full-Scale Offensive',
    'event_16': 'Virtual Tactical Simulation',
    'event_161': "Golden Autumn's Invitation",
    'event_17': 'Galactic Disaster Dispatch Preparation',
    'event_18': 'The Month Together Beneath the Starshine',
    'event_19': "Rei's Gift",
    'event_2': 'The Path of a Captain',
    'event_20': 'Chasing the Star\u2019s Trajectory',
    'event_2026newyear': 'Toward the First Light',
    'event_21': 'See you on the Unigram',
    'event_22': 'Virtual Tactical Simulation',
    'event_23': 'Virtual Tactical Simulation',
    'event_24': 'Memoirs of the Ark Protection Bureau Chief',
    'event_25': 'Overdrive - Simulation',
    'event_26': 'Garden Cafe\u2019s Returnee Present',
    'event_27': 'Basin of Hyperspace - Dimensional Twilight',
    'event_28': 'Toward the First Light',
    'event_29': 'Law of Preserved Hope in Confinement',
    'event_3': 'Rookie Captain Mission',
    'event_30': 'Happy New Year 2026!',
    'event_31': "Rei's Gift",
    'event_32': 'Basin of Hyperspace - Dimensional Twilight',
    'event_33': 'Guardian of the Ark',
    'event_34': 'Emergency Rescue Protocol',
    'event_35': 'Overdrive - Simulation',
    'event_36': 'Basin of Hyperspace - Dimensional Twilight',
    'event_38': 'Galactic News Network',
    'event_39': 'Virtual Tactical Simulation',
    'event_4': 'A Flickering Gleam on a Rusted Anchor',
    'event_40': 'Spiral Tower of Screams',
    'event_42': 'Galactic Disaster',
    'event_43': '9th Street Mercenary Office',
    'event_44': 'Special Exploration Reward - Burning Life',
    'event_45': 'Bonds of Time',
    'event_46': 'Guardian of the Ark',
    'event_47': 'Back to Codex',
    'event_48': 'Chaos Regular Survey',
    'event_49': "Monsters' Arena",
    'event_5': 'Journey of Healing: Rei',
    'event_50': "Rei's Gift",
    'event_51': 'Basin of Hyperspace - Dimensional Twilight',
    'event_52': 'Overdrive - Simulation',
    'event_54': 'Basin of Hyperspace - Dimensional Twilight',
    'event_55': "Speitz's Shadow",
    'event_56': 'Virtual Tactical Simulation',
    'event_58': 'Emergency Rescue Protocol',
    'event_59': 'Chrono Archon of All Universal Events',
    'event_6': 'Basin of Hyperspace - Dimensional Twilight',
    'event_60': 'Virtual Tactical Simulation',
    'event_61': 'Overdrive - Simulation',
    'event_62': 'Sweet Rewards After Missions',
    'event_64': 'Basin of Hyperspace - Dimensional Twilight',
    'event_65': 'Operation: Firebreak',
    'event_66': 'Operation: Rescue Diana',
    'event_67': 'Virtual Tactical Simulation',
    'event_68': 'Virtual Tactical Simulation',
    'event_69': 'Special Guests',
    'event_7': 'Galactic Disaster',
    'event_70': 'Festival Missions',
    'event_71': 'Galactic News Network',
    'event_72': 'Full-Scale Offensive',
    'event_73': 'Overdrive - Simulation',
    'event_75': 'Love Gathered at the Wingtips',
    'event_76': 'Special Guests',
    'event_77': "Days Carrying the Successor's Will",
    'event_78': 'SS Edenity Patrol Operation',
    'event_79': 'Special Gift',
    'event_8': 'Galactic News Network',
    'event_80': "Melody's Trail",
    'event_81': 'Galactic News Network',
    'event_82': 'Galactic Disaster',
    'event_83': 'Enjoy the Festival',
    'event_84': 'Virtual Tactical Simulation',
    'event_85': 'Chaos Regular Survey',
    'event_86': 'Zero System',
    'event_87': 'Overdrive - Simulation',
    'event_88': 'Overdrive - Simulation',
    'event_89': 'Basin of Hyperspace - Dimensional Twilight',
    'event_9': 'Zero System',
    'event_90': 'Basin of Hyperspace - Dimensional Twilight',
    'event_91': 'The Shadow Under the Willow',
    'event_92': 'Sortie Support',
    'event_93': 'Chaos Sortie Operation',
    'event_94': 'Lost Fairy Tale Book',
    'event_95': 'Full-Scale Offensive',
    'event_96': 'Abundant Return Gift',
    'event_97': 'Grand Welcome Check-In',
    'event_98': "Successor's Guiding Light",
    'event_99': 'Emergency Rescue Protocol',
    'event_anniversary_gacha_1': 'Operation: Rescue Diana',
    'event_arena_1': "Monsters' Arena",
    'event_arena_2': "Monsters' Arena",
    'event_bartender_01': 'SE-4 BR33ZE',
    'event_bartender_1': 'SE-4 BR33ZE',
    'event_chaos_assault_1': 'Chaos Sortie Operation',
    'event_chaos_assault_support_1': 'Sortie Support',
    'event_chaos_inspection_1': 'Chaos Regular Survey',
    'event_chaos_inspection_2': 'Chaos Regular Survey',
    'event_codex_mission_1': 'Back to Codex',
    'event_collab_coupon': 'CZN x Epic Seven',
    'event_combatant_trial_1': 'Virtual Tactical Simulation - Yuki',
    'event_combatant_trial_10': 'Virtual Tactical Simulation - Heidemarie',
    'event_combatant_trial_11': 'Virtual Tactical Simulation - Adelheid',
    'event_combatant_trial_12': 'Virtual Tactical Simulation - Tenebria',
    'event_combatant_trial_13': 'Virtual Tactical Simulation - Hilde',
    'event_combatant_trial_14': 'Virtual Tactical Simulation - Yuki',
    'event_combatant_trial_15': 'Virtual Tactical Simulation - Arabella',
    'event_combatant_trial_16': 'Virtual Tactical Simulation - Haru',
    'event_combatant_trial_17': 'Virtual Tactical Simulation - Olga',
    'event_combatant_trial_2': 'Virtual Tactical Simulation - Chizuru',
    'event_combatant_trial_3': 'Virtual Tactical Simulation - Sereniel',
    'event_combatant_trial_4': 'Virtual Tactical Simulation - Narja',
    'event_combatant_trial_5': 'Virtual Tactical Simulation - Nine',
    'event_combatant_trial_6': 'Virtual Tactical Simulation - Tiphera',
    'event_combatant_trial_7': 'Virtual Tactical Simulation - Rita',
    'event_combatant_trial_8': 'Virtual Tactical Simulation - Diana',
    'event_combatant_trial_9': 'Virtual Tactical Simulation - Fei',
    'event_combatant_trial_999': 'Virtual Tactical Simulation - Heidemarie',
    'event_daily_1': 'Invitation to a New Journey',
    'event_daily_10': "Rei's Gift",
    'event_daily_11': 'Emergency Rescue Protocol',
    'event_daily_12': "Days Carrying the Successor's Will",
    'event_daily_13': 'Emergency Rescue Protocol',
    'event_daily_15': "Rei's Gift",
    'event_daily_16': "Rei's Gift",
    'event_daily_2': "Rei's Gift",
    'event_daily_3': "Rei's Gift",
    'event_daily_4': 'Galactic Disaster Dispatch Preparation',
    'event_daily_5': 'The Month Together Beneath the Starshine',
    'event_daily_6': "Rei's Gift",
    'event_daily_7': 'Happy New Year 2026!',
    'event_daily_8': "Rei's Gift",
    'event_daily_9': 'Emergency Rescue Protocol',
    'event_daily_half_anni_1': 'Special Gift',
    'event_daily_holiday_01': "Golden Autumn's Invitation",
    'event_daily_mission_check_1': 'Lost Fairy Tale Book',
    'event_devil_01': "Olga's Secret Diary \u2661",
    'event_director_01': 'Memoirs of the Ark Protection Bureau Chief',
    'event_director_02': 'Memoirs of the Ark Protection Bureau Chief',
    'event_disaster_s05_c0': 'Escape from Judgment',
    'event_get_character_1': 'Journey of Healing: Rei',
    'event_half_year_mission_1': 'Festival Missions',
    'event_idol_01': '[Scoop] Up Close with Tenebria',
    'event_main_story_again_01': 'A Story Rewritten',
    'event_messenger_01': 'See you on the Unigram',
    'event_nodelist_001': '9th Street Mercenary Office',
    'event_nodelist_002': "Speitz's Shadow",
    'event_nodelist_003': 'Love Gathered at the Wingtips',
    'event_nodelist_004': 'The Shadow Under the Willow',
    'event_nodelist_005': 'Invitation to Dreams',
    'event_nodelist_006': "Following the Fox's Footsteps",
    'event_nodelist_007': 'Primal Desire',
    'event_nodelist_008': "Guardian Angel's Vacation",
    'event_overclock_live_01': 'Overdrive - Simulation',
    'event_overclock_live_02': 'Overdrive - Simulation',
    'event_overclock_live_03': 'Overdrive - Simulation',
    'event_overclock_live_04': 'Overdrive - Simulation',
    'event_overclock_live_05': 'Overdrive - Simulation',
    'event_overclock_live_06': 'Overdrive - Simulation',
    'event_overclock_live_07': 'Overdrive - Simulation',
    'event_overclock_live_08': 'Overdrive - Simulation',
    'event_overclock_live_09': 'Overdrive - Simulation',
    'event_overclock_live_10': 'Overdrive - Simulation',
    'event_overclock_live_11': 'Overdrive - Simulation',
    'event_overclock_live_12': 'Overdrive - Simulation',
    'event_overclock_live_13': 'Overdrive - Simulation',
    'event_overclock_live_14': 'Overdrive - Simulation',
    'event_policy_1': 'Guardian of the Ark',
    'event_policy_2': 'Guardian of the Ark',
    'event_policy_3': 'Guardian of the Ark',
    'event_policy_4': 'Guardian of the Ark',
    'event_policy_5': 'Guardian of the Ark',
    'event_recorder_01': 'Chrono Archon of All Universal Events',
    'event_return_01': 'Garden Cafe\u2019s Returnee Present',
    'event_return_02': 'Abundant Return Gift',
    'event_return_03': 'Grand Festival',
    'event_return_daily_check_01': 'Grand Welcome Check-In',
    'event_return_daily_check_02': 'Visit the Festival',
    'event_schedule_2026newyear': 'Toward the First Light',
    'event_schedule_cdx_mission_1': 'Back to Codex',
    'event_schedule_devil_001': "Olga's Secret Diary \u2661",
    'event_schedule_director_001': 'Memoirs of the Ark Protection Bureau Chief',
    'event_schedule_director_002': 'Memoirs of the Ark Protection Bureau Chief',
    'event_schedule_gacha_event_1': 'Operation: Rescue Diana',
    'event_schedule_half_year_ch_1': 'Special Guests',
    'event_schedule_half_year_ch_2': 'Special Guests',
    'event_schedule_half_year_ms_1': 'Festival Missions',
    'event_schedule_idol_001': '[Scoop] Up Close with Tenebria',
    'event_schedule_love_2': 'Sweet Rewards After Missions',
    'event_schedule_love_3': 'Sweet Rewards After Missions',
    'event_schedule_love_4': 'Sweet Rewards After Missions',
    'event_schedule_love_5': 'Sweet Rewards After Missions',
    'event_schedule_policy_001': 'Guardian of the Ark',
    'event_schedule_policy_002': 'Guardian of the Ark',
    'event_schedule_policy_003': 'Guardian of the Ark',
    'event_schedule_policy_004': 'Guardian of the Ark',
    'event_schedule_policy_005': 'Guardian of the Ark',
    'event_schedule_recorder_001': 'Chrono Archon of All Universal Events',
    'event_season_1_daily_1': 'Chasing the Star\u2019s Trajectory',
    'event_season_2_daily_1': 'Bonds of Time',
    'event_season_3_daily_1': "Melody's Trail",
    'event_season_4_daily_1': 'Chasing the Remnants of Light',
    'event_season_love_2': 'Sweet Rewards After Missions',
    'event_season_love_3': 'Sweet Rewards After Missions',
    'event_season_love_4': 'Sweet Rewards After Missions',
    'event_season_love_5': 'Sweet Rewards After Missions',
    'event_stock_01': 'Stella Market',
    'event_stock_1': 'Stella Market',
    'event_summer_01': 'Beach Caf\xe9 Festival',
    'evn_trc_1052_1': 'Law of Preserved Hope in Confinement',
    'evn_trc_1062_1': 'A Flickering Gleam on a Rusted Anchor',
    'evn_trc_30048_1': "Successor's Guiding Light",
    'hyperspace_02_01': 'Basin of Hyperspace - Dimensional Twilight',
    'hyperspace_02_02': 'Basin of Hyperspace - Dimensional Twilight',
    'hyperspace_02_03': 'Basin of Hyperspace - Dimensional Twilight',
    'hyperspace_02_04': 'Basin of Hyperspace - Dimensional Twilight',
    'hyperspace_02_05': 'Basin of Hyperspace - Dimensional Twilight',
    'hyperspace_02_06': 'Basin of Hyperspace - Dimensional Twilight',
    'hyperspace_02_07': 'Basin of Hyperspace - Dimensional Twilight',
    'hyperspace_02_08': 'Basin of Hyperspace - Dimensional Twilight',
    'hyperspace_02_09': 'Basin of Hyperspace - Dimensional Twilight',
    'hyperspace_02_10': 'Basin of Hyperspace - Dimensional Twilight',
    'hyperspace_02_11': 'Basin of Hyperspace - Dimensional Twilight',
    'hyperspace_02_12': 'Basin of Hyperspace - Dimensional Twilight',
    'hyperspace_02_13': 'Basin of Hyperspace - Dimensional Twilight',
    'hyperspace_02_14': 'Basin of Hyperspace - Dimensional Twilight',
    'hyperspace_02_15': 'Basin of Hyperspace - Dimensional Twilight',
    'hyperspace_02_16': 'Basin of Hyperspace - Dimensional Twilight',
    'hyperspace_02_17': 'Basin of Hyperspace - Dimensional Twilight',
    'hyperspace_02_18': 'Basin of Hyperspace - Dimensional Twilight',
    'level_up_1': 'The Path of a Captain',
    'marble_s01': 'SS Edenity Patrol Operation',
    'remnants_boss_penalty_002': 'Full-Scale Offensive',
    'remnants_boss_penalty_003': 'Full-Scale Offensive',
    'remnants_boss_penalty_004': 'Full-Scale Offensive',
    'remnants_boss_penalty_005': 'Full-Scale Offensive',
    'remnants_boss_penalty_006': 'Full-Scale Offensive',
    'schedule_trc_1052': 'Law of Preserved Hope in Confinement',
    'schedule_trc_1062': 'A Flickering Gleam on a Rusted Anchor',
    'schedule_trc_30048': "Successor's Guiding Light",
    'spiral_tower_01': 'Spiral Tower of Screams',
    'zero_orb_1': 'Zero System',
    'zero_orb_3': 'Zero System',
    'zero_orb_4': 'Zero System',
    'zero_orb_5': 'Zero System',
    'zero_orb_ch_1': 'Zero System',
    'zero_orb_ch_2': 'Zero System',
}

# {combatant res_id: Excursion types}. See game_client.excursion_types.
EXCURSION_TYPES = {
    1003: 7,
    1004: 7,
    1005: 7,
    1007: 7,
    1008: 7,
    1009: 7,
    1010: 7,
    1012: 7,
    1015: 7,
    1017: 7,
    1018: 7,
    1019: 7,
    1020: 7,
    1021: 7,
    1024: 7,
    1027: 7,
    1028: 7,
    1033: 7,
    1039: 7,
    1040: 7,
    1041: 7,
    1043: 7,
    1049: 7,
    1050: 7,
    1052: 7,
    1054: 7,
    1055: 7,
    1056: 10,
    1057: 7,
    1060: 7,
    1061: 7,
    1062: 7,
    1063: 7,
    1064: 7,
    1069: 7,
    30047: 7,
    30048: 7,
    30075: 11,
    30084: 10,
    30093: 11,
    30097: 10,
    30113: 11,
    30115: 11,
    30117: 11,
}
